id: P694559F6
initial_creation_type: ocr
source_metadata:
  volumes:
    c3da4adecf2841a68df321191a0bceb5:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: ཚོགས་ཀྱི་གཏམ།
      total_pages: 1144
      volume_number: 96
